Refactor the env variables in GitHub workflows (#237)
* Refactor the env variables in GitHub workflows
Fixes #234

* Coderabbit

* Fix indentation

diff --git a/.github/workflows/deploy-prod.yaml b/.github/workflows/deploy-prod.yaml
--- a/.github/workflows/deploy-prod.yaml
+++ b/.github/workflows/deploy-prod.yaml
@@ -82,22 +82,29 @@ jobs:
       url: ${{ vars.APP_BASE_URL }}
 
     env:
-      API_KEY: ${{ secrets.API_KEY }}
       API_BASE_URL: ${{ vars.API_BASE_URL }}
+      API_KEY: ${{ secrets.API_KEY }}
       APP_BASE_URL: ${{ vars.APP_BASE_URL }}
-      CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
-      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
-      DEPLOY_ENV: ${{ vars.DEPLOY_ENV }}
       AUTH0_AUDIENCE: ${{ vars.AUTH0_AUDIENCE }}
       AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
       AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
       AUTH0_DOMAIN: ${{ vars.AUTH0_DOMAIN }}
       AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
+      CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
+      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
+      DEPLOY_ENV: ${{ vars.DEPLOY_ENV }}
 
     permissions:
       contents: read
 
     steps:
+      - name: Assert DEPLOY_ENV
+        run: |
+          if [ -z "${{ vars.DEPLOY_ENV }}" ]; then
+            echo "Error: DEPLOY_ENV is not set"
+            exit 1
+          fi
+
       - name: Checkout code
         uses: actions/checkout@v4
 
@@ -123,9 +130,9 @@ jobs:
         working-directory: ./out/apps/web
         # Wrangler secret put takes the value as a piped input.
         run: |
-          echo "${{ secrets.API_KEY }}" | pnpx wrangler secret put API_KEY --env prod
-          echo "${{ secrets.AUTH0_SECRET }}" | pnpx wrangler secret put AUTH0_SECRET --env prod
-          echo "${{ secrets.AUTH0_CLIENT_SECRET }}" | pnpx wrangler secret put AUTH0_CLIENT_SECRET --env prod
+          echo "${{ secrets.API_KEY }}" | pnpx wrangler secret put API_KEY --env ${{ vars.DEPLOY_ENV }}
+          echo "${{ secrets.AUTH0_SECRET }}" | pnpx wrangler secret put AUTH0_SECRET --env ${{ vars.DEPLOY_ENV }}
+          echo "${{ secrets.AUTH0_CLIENT_SECRET }}" | pnpx wrangler secret put AUTH0_CLIENT_SECRET --env ${{ vars.DEPLOY_ENV }}
 
       - name: Deploy to site to Cloudflare
         working-directory: ./out
